export enum LanguageNames {
  en = 'English',
  es = 'Español',
  fr = 'Français',
  de = 'Deutsch',
  it = 'Italiano',
  pt = 'Português',
  ru = 'Русский',
  zh = '中文',
  ja = '日本語',
  ko = '한국어',
  ar = 'العربية',
  hi = 'हिन्दी',
  bn = 'বাংলা',
  ur = 'اردو',
  tr = 'Türkçe',
  nl = 'Nederlands',
  pl = 'Polski',
  sv = 'Svenska',
  ro = 'Română',
  fa = 'فارسی',
}

export enum PrintButtonLanguage {
  en = 'Print / Save PDF',
  es = 'Imprimir / Guardar PDF',
  fr = 'Imprimer / Enregistrer le PDF',
  de = 'Drucken / PDF speichern',
  it = 'Stampa / Salva PDF',
  pt = 'Imprimir / Salvar PDF',
  ru = 'Печать / Сохранить PDF',
  zh = '打印 / 保存 PDF',
  ja = '印刷 / PDF を保存',
  ko = '인쇄 / PDF 저장',
  ar = 'طباعة / حفظ PDF',
  hi = 'प्रिंट करें / PDF सहेजें',
  bn = 'প্রিন্ট / পিডিএফ সংরক্ষণ করুন',
  ur = 'پرنٹ کریں / PDF محفوظ کریں',
  tr = 'Yazdır / PDF Kaydet',
  nl = 'Afdrukken / PDF opslaan',
  pl = 'Drukuj / Zapisz PDF',
  sv = 'Skriv ut / Spara PDF',
  ro = 'Printează / Salvează PDF',
  fa = 'چاپ / ذخیره PDF',
}